#!/bin/sh
### BEGIN INIT INFO
# Provides:          headlessx
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Sets up a Headless X Server using Xvfb
# Description:       Sets up a Headless X Server using Xvfb
### END INIT INFO

DESC="Headless X Server"
NAME=headlessx
#DAEMON=

do_start()
{
   echo "starting Headless X!";
   Xvfb -screen 0 800x600x16 -ac &
   DISPLAY=:0 ratpoison &
}

do_stop()
{
   echo "stopping Headless X!"
}


case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
esac

exit 0
